defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

predictions_path: ../../sample_predictions/0.parquet
output_dir: ../../sample_output
samples_per_subject: 4
resampling_seed: 0

hydra:
  output_subdir: null
  run:
    dir: .
